# JWT 관련 설정
jwt:
  secret: "1@Ml9demE7lEwK#zc3v5X!d29yM6s8@j#DYSycrhk0fYm1HdU!TyGv14SSIpdf" # 토큰 서명에 사용할 비밀 키
  accessTokenExpiration: 3600000       # Access Token 유효 기간 (밀리초  1시간 3600000)
  refreshTokenExpiration: 86400000    # Refresh Token 유효 기간 (밀리초, 24시간 86400000)
  cookieMaxAge: 86400               # Cookie 유효 기간 (초, 24시간) :Refresh Token은 cookie에 보내므로 refreshtoken과 같은 기간을 줌

# 카카오 알림톡 설정
alimtalk:
  tokenUrl: https://www.biztalk-api.com/v2/auth/getToken
  sendUrl: https://www.biztalk-api.com/v2/kko/sendAlimTalk
  resultUrl: https://www.biztalk-api.com/v2/kko/getResultAll
  bsid: wisam
  passwd: b14c2d414288409ff3948159e1b9306c7c48a302
  senderKey: 4946de9fe9945a158bf5b9a47c8bbc7e6d3ceeb5
  templateCode: bidawardnotice
  countryCode: "82"
  # excel로 제공된 정보 (사용하지 않음)
  # clientId : "wisam"          
  # clientSecret : "66fd8d80344a5bb4b28f85ee02cd378178bacf8e"

# coolsms 인증번호 전송용 설정정
coolsms:
  apiKey: "NCS547958B8DCD89"        
  apiSecretKey: "0FC78662787861FB62E9349FDA63A75B" 
  # sendProfileKey : "66fd8d80344a5bb4b28f85ee02cd378178bacf8e"
  provider: "https://api.coolsms.co.kr"
  sender: "024475967"               
  expirationTimeInMinutes: 3

# inicis 결제 및 승인 요청 설정정
inicis:
  params:
    version: "1.0"
    mid: "INIpayTest"
    currency: "WON"
    acceptMethod: "HPP(1):va_receipt:below1000:centerCd(Y)"
    gopayMethod: "Card:DirectBank:VBank:HPP"
    signKey: "SU5JTElURV9UUklQTEVERVNfS0VZU1RS"
    use_chkfake: "Y"

  idcName:
    fc: "fc"
    ks: "ks"
    stg: "stg"

  returnUrls:
    return: "http://localhost:5000/api/pgreturn"
    returnMobile: "http://localhost:5000/api/pgreturn-mobile"
    close: "http://localhost:5000/api/pgclose"
    redirect: "http://localhost:9000/bidseats"
    login: "http://localhost:9000/userlogin"

  views:
    request: "INIstdpay_pc_req"
    return: "INIstdpay_pc_return"
    requestMobile: "INImobile_mo_req"        # 결제창 시작 전 확인 화면
    returnMobile: "INImobile_mo_return"     # 승인 후 리턴 화면
    close: "close"
    error: "error"

  urls:
    auth:
      fc: "https://fcstdpay.inicis.com/api/payAuth"
      ks: "https://ksstdpay.inicis.com/api/payAuth"
      stg: "https://stgstdpay.inicis.com/api/payAuth"
      default: "https://defaultstdpay.inicis.com/api/payAuth"

    netCancel:
      fc: "https://fcstdpay.inicis.com/api/netCancel"
      ks: "https://ksstdpay.inicis.com/api/netCancel"
      stg: "https://stgstdpay.inicis.com/api/netCancel"
      default: "https://defaultstdpay.inicis.com/api/netCancel"

    mobilePayReq:
      fc: "https://fcmobile.inicis.com/smart/payReq.ini"
      ks: "https://ksmobile.inicis.com/smart/payReq.ini"
      stg: "https://stgmobile.inicis.com/smart/payReq.ini"
      default: "https://default.inicis.com/smart/payReq.ini"

